export const CATALOG = [
  { slug: "sky-buddies", emoji: "✈️", name: "Sky Buddies", tag: "Endless 3-lane flyer", vibe: "3d", art: "linear-gradient(160deg, #0ea5e9, #f9a8d4 70%, #fde68a)" },
  { slug: "flag-dash", emoji: "🏁", name: "Flag Dash", tag: "Stair race to the flag", vibe: "jump", art: "linear-gradient(160deg, #86efac, #fde68a)" },
  { slug: "bounce-caps", emoji: "🍄", name: "Bounce Caps", tag: "Mushroom coin hunt", vibe: "jump", art: "linear-gradient(160deg, #fb7185, #fbbf24)" },
  { slug: "frost-slide", emoji: "🧊", name: "Frost Slide", tag: "Skate the ice lakes", vibe: "jump", art: "linear-gradient(160deg, #bae6fd, #e0f2fe)" },
  { slug: "cloud-hop", emoji: "☁️", name: "Cloud Hop", tag: "Race up the sky", vibe: "jump", art: "linear-gradient(160deg, #7dd3fc, #f9a8d4)" },
  { slug: "bubbly-bay", emoji: "🫧", name: "Bubbly Bay", tag: "Pearl dive past jellies", vibe: "jump", art: "linear-gradient(160deg, #22d3ee, #2563eb)" },
  { slug: "critter-ride", emoji: "🦕", name: "Critter Ride", tag: "Steer and jump the pits", vibe: "jump", art: "linear-gradient(160deg, #4ade80, #facc15)" },
  { slug: "bubble-blaster", emoji: "🫧", name: "Bubble Blaster", tag: "Pop blobs with bubbles", vibe: "blast", art: "linear-gradient(160deg, #38bdf8, #a78bfa)" },
  { slug: "star-shower", emoji: "🌟", name: "Star Shower", tag: "Sky beam shmup", vibe: "blast", art: "linear-gradient(160deg, #1e1b4b, #fbbf24)" },
  { slug: "paint-arena", emoji: "🎨", name: "Paint Arena", tag: "Twin-stick splat", vibe: "blast", art: "linear-gradient(160deg, #fb7185, #38bdf8)" },
  { slug: "balloon-boss", emoji: "🎈", name: "Balloon Boss", tag: "Pop the giant balloon", vibe: "blast", art: "linear-gradient(160deg, #f472b6, #fde68a)" },
  { slug: "kart-cruise", emoji: "🏎️", name: "Kart Cruise", tag: "Steer lanes, 2-lap cups", vibe: "race", art: "linear-gradient(160deg, #f97316, #facc15)" },
  { slug: "sky-lanes", emoji: "🌈", name: "Sky Lanes", tag: "3D lane dash", vibe: "3d", art: "linear-gradient(160deg, #818cf8, #7dd3fc)" },
  { slug: "sled-zoom", emoji: "🛷", name: "Sled Zoom", tag: "Slide, hop, sip cocoa", vibe: "race", art: "linear-gradient(160deg, #e0f2fe, #93c5fd)" },
  { slug: "sunny-soccer", emoji: "⚽", name: "Sunny Soccer", tag: "First to 3 goals", vibe: "sport", art: "linear-gradient(160deg, #4ade80, #86efac)" },
  { slug: "beach-volley", emoji: "🏐", name: "Beach Volley", tag: "Over the net", vibe: "sport", art: "linear-gradient(160deg, #fde68a, #fb923c)" },
  { slug: "paddy-pong", emoji: "🏓", name: "Paddy Pong", tag: "Bouncy paddle duel", vibe: "sport", art: "linear-gradient(160deg, #fb7185, #fbbf24)" },
  { slug: "air-puck", emoji: "🏒", name: "Air Puck", tag: "Table hockey zoom", vibe: "sport", art: "linear-gradient(160deg, #38bdf8, #e0f2fe)" },
  { slug: "tug-stars", emoji: "⭐", name: "Tug Stars", tag: "Pull the sparkle", vibe: "sport", art: "linear-gradient(160deg, #fbbf24, #fb7185)" },
  { slug: "hot-spud", emoji: "🥔", name: "Hot Spud", tag: "Pass the potato", vibe: "sport", art: "linear-gradient(160deg, #fdba74, #fb7185)" },
  { slug: "block-buddies", emoji: "📦", name: "Block Buddies", tag: "Push crates together", vibe: "puzzle", art: "linear-gradient(160deg, #fbbf24, #86efac)" },
  { slug: "mirror-maze", emoji: "🪞", name: "Mirror Maze", tag: "Dad moves mirrored", vibe: "puzzle", art: "linear-gradient(160deg, #c4b5fd, #f9a8d4)" },
  { slug: "color-dash", emoji: "🎯", name: "Color Dash", tag: "Stand on the color", vibe: "puzzle", art: "linear-gradient(160deg, #f472b6, #22d3ee)" },
  { slug: "flip-race", emoji: "🃏", name: "Flip Race", tag: "Memory match race", vibe: "puzzle", art: "linear-gradient(160deg, #a78bfa, #fde68a)" },
  { slug: "tower-stack", emoji: "🗼", name: "Tower Stack", tag: "Catch and stack", vibe: "puzzle", art: "linear-gradient(160deg, #fb923c, #fbbf24)" },
  { slug: "pillow-pop", emoji: "🛏️", name: "Pillow Pop", tag: "Soft pillow bumps", vibe: "bump", art: "linear-gradient(160deg, #fbcfe8, #c4b5fd)" },
  { slug: "snow-puff", emoji: "❄️", name: "Snow Puff", tag: "Snowball splat", vibe: "bump", art: "linear-gradient(160deg, #e0f2fe, #38bdf8)" },
  { slug: "sumo-bump", emoji: "🍩", name: "Sumo Bump", tag: "Bounce out the ring", vibe: "bump", art: "linear-gradient(160deg, #fbbf24, #f97316)" },
  { slug: "coin-dash", emoji: "🪙", name: "Coin Dash", tag: "Grab the coins", vibe: "grab", art: "linear-gradient(160deg, #facc15, #fb923c)" },
  { slug: "fruit-catch", emoji: "🍎", name: "Fruit Catch", tag: "Baskets up", vibe: "grab", art: "linear-gradient(160deg, #4ade80, #fb7185)" },
  { slug: "bubble-pop", emoji: "🧼", name: "Bubble Pop", tag: "Poke rising bubbles", vibe: "grab", art: "linear-gradient(160deg, #67e8f9, #a78bfa)" },
  { slug: "pet-rescue", emoji: "🐾", name: "Pet Rescue", tag: "Free the fluffies", vibe: "grab", art: "linear-gradient(160deg, #86efac, #f9a8d4)" },
  { slug: "ring-glide", emoji: "💍", name: "Ring Glide", tag: "Fly the hoop course", vibe: "3d", art: "linear-gradient(160deg, #38bdf8, #fde68a)" },
  { slug: "maze-marble", emoji: "🔮", name: "Maze Marble", tag: "Roll to the hole", vibe: "3d", art: "linear-gradient(160deg, #34d399, #0ea5e9)" },
  { slug: "space-pads", emoji: "🚀", name: "Space Pads", tag: "Hop the moon pads", vibe: "3d", art: "linear-gradient(160deg, #1e1b4b, #a78bfa)" },
  { slug: "noodle-duel", emoji: "🍜", name: "Noodle Duel", tag: "Grow a snack snake", vibe: "classic", art: "linear-gradient(160deg, #4ade80, #f472b6)" },
  { slug: "glow-trails", emoji: "⚡", name: "Glow Trails", tag: "Light-cycle zoom", vibe: "classic", art: "linear-gradient(160deg, #22d3ee, #fb7185)" },
  { slug: "block-drop", emoji: "🧱", name: "Block Drop", tag: "Clear lines first", vibe: "classic", art: "linear-gradient(160deg, #818cf8, #fb7185)" },
  { slug: "four-connect", emoji: "🔴", name: "Four Connect", tag: "Make a happy four", vibe: "classic", art: "linear-gradient(160deg, #fb7185, #fbbf24)" },
  { slug: "mole-duel", emoji: "🐹", name: "Mole Duel", tag: "Whack your moles", vibe: "classic", art: "linear-gradient(160deg, #86efac, #fbbf24)" },
  { slug: "simon-spark", emoji: "✨", name: "Simon Spark", tag: "Copy the sparkles", vibe: "classic", art: "linear-gradient(160deg, #c4b5fd, #38bdf8)" }
];

export const VIBES = [
  { id: "all", label: "All" },
  { id: "jump", label: "Jump" },
  { id: "blast", label: "Blast" },
  { id: "race", label: "Race" },
  { id: "sport", label: "Sport" },
  { id: "puzzle", label: "Puzzle" },
  { id: "bump", label: "Bump" },
  { id: "grab", label: "Grab" },
  { id: "3d", label: "3D" },
  { id: "classic", label: "Classic" }
];
